Morph
	subclass: #StarSqueakMorph
	instanceVariableNames:
		'dimensions pixelsPerPatch patchVariables patchVariableToDisplay logPatchVariableScale patchVarDisplayForm patchForm patchColorSetter patchColorGetter turtles turtleDemons worldDemons sniffRange scaledEvaporationRate diffusionRate lastTurtleID generation running stepTime turtlesAtPatchCache turtlesAtPatchCacheValid'
	classVariableNames: 'RandomSeed'
	poolDictionaries: ''
	category: 'StarSqueak-Kernel'