Model
	subclass: #PDA
	instanceVariableNames:
		'userCategories allPeople allEvents recurringEvents allToDoItems allNotes date category currentItem currentItemText currentItemSelection categoryList categoryListIndex peopleList peopleListIndex scheduleList scheduleListIndex toDoList toDoListIndex notesList notesListIndex dateButtonPressed viewDescriptionOnly '
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-PDA'