Morph
	subclass: #SketchEditorMorph
	instanceVariableNames:
		'hostView stampForm canvasRectangle palette currentColor ticksToDwell rotationCenter registrationPoint newPicBlock emptyPicBlock action paintingForm dimForm buff brush paintingFormPen formCanvas picToBuff brushToBuff buffToBuff buffToPic rotationButton scaleButton strokeOrigin cumRot cumMag undoBuffer lastEvent currentNib enclosingPasteUpMorph '
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Support'