WonderlandMorph
	subclass: #WonderlandCameraMorph
	instanceVariableNames:
		'myCamera myControls eventFocus lastCursorPoint mouseUpButton firstPersonControls mode outline currentActor currentPosition currentCanvas currentColor currentNib lastPosition paintMode palette restore backup pickedPoint pickedActor myRenderer'
	classVariableNames: 'CachedNibs'
	poolDictionaries: 'WonderlandConstants'
	category: 'Balloon3D-Wonderland-Morphs'