primitiveHeaderString: tricky			"InterpreterSupportCode primitiveHeaderString: self trickyPrimitiveList"
	"Answer the contents of the primitives.h file."

	^String streamContents: [:file |
		file nextPutAll: '// primitives.h -- primitive characteristics'; cr;
			nextPutAll: '//'; cr;
			nextPutAll: '// WARNING: this file was generated automatically -- DO NOT EDIT!'; cr;
			nextPutAll: '//'; cr;
			nextPutAll: '// Author: Squeak2.7 (on behalf of Ian.Piumarta@INRIA.Fr)'; cr;
			nextPutAll: '//'; cr;
			nextPutAll: '// Last edited: NEVER (and woebetide anybody who dares to!)'; cr; cr.
		self nextPutExternDeclarations: tricky on: file.
	]