FlashFileReader
	subclass: #FlashMorphReader
	instanceVariableNames:
		'location fillStyles lineStyles shapes fonts forms sounds buttons lineSequence currentShape player spriteOwners stepTime frameRate frame activeMorphs passiveMorphs activeFont textOffset textHeight textMorph canCompressPoints pointList compressionBounds fillIndex0 fillIndex1 lineStyleIndex leftFillList rightFillList lineStyleList streamingSound morphedFillStyles morphedLineStyles'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Flash-Import'