ImageMorph
	subclass: #PaintBoxMorph
	instanceVariableNames:
		'action tool currentCursor thumbnail currentColor currentBrush colorMemory colorPatch stampHolder rotationTabForm scaleTabForm colorMemoryThin brushes focusMorph weakDependents recentColors '
	classVariableNames: 'AllOffImage AllOnImage AllPressedImage ColorChart OriginalBounds Prototype '
	poolDictionaries: ''
	category: 'Morphic-Support'