initialValuesAToM
	"CategoryInfo _ nil"
	"Preferences openFactoredPanel"
	^#(
		(annotationPanes					false	(browsing))
		(autoAccessors						false	(general))
		(automaticViewerPlacement			true	(scripting))
		(balloonHelpEnabled					true	(morphic))
		(browserShowsPackagePane			false	(browsing))
		(browseWithPrettyPrint				false	(browsing))
		(caseSensitiveFinds					false	(general))
		(cautionBeforeClosing				false	(windows))
		(changeSetVersionNumbers			true	(fileout))
		(checkForSlips						true	(fileout))
		(clickOnLabelToEdit					true	(windows))
		(cmdDotEnabled						true	(debug))
		(colorWhenPrettyPrinting			false	(browsing))
		(compressFlashImages				false	(media))
		(confirmFirstUseOfStyle				true	(browsing))
		(conversionMethodsAtFileOut			false	(fileout))
		(debugHaloHandle					true	(debug halos))
		(diffsInChangeList					true	(browsing))
		(extractFlashInHighQuality			true	(media))
		(extractFlashInHighestQuality		false	(media))
		(fastDragWindowForMorphic			false	(windows))
		(fenceEnabled						true	(scripting))
		(ignoreStyleIfOnlyBold				true	(browsing))
		(inboardScrollbars					false	(scrolling))
		(logDebuggerStackToFile				true	(debug))
		(menuColorFromWorld				false	(menus))
		(mvcProjectsAllowed					false	(general))
)
