MouseMenuController
	subclass: #FormEditor
	instanceVariableNames: 'form tool grid togglegrid mode previousTool color unNormalizedColor xgridOn ygridOn '
	classVariableNames:
		'YgridKey OverKey YellowButtonMenu RepeatCopyKey SingleCopyKey InKey BlackKey OutKey LineKey TogglexGridKey FlashCursor DarkGrayKey ChangeGridsKey GrayKey SelectKey UnderKey ReverseKey WhiteKey BlockKey LightGrayKey CurveKey BitEditKey YellowButtonMessages EraseKey ToggleyGridKey '
	poolDictionaries: ''
	category: 'Graphics-Editors'