Object
	subclass: #HtmlFormatter
	instanceVariableNames:
		'browser baseUrl formDatas outputStream preformattedLevel indentLevel boldLevel italicsLevel underlineLevel strikeLevel centerLevel urlLink listLengths listTypes precedingSpaces precedingNewlines morphsToEmbed incompleteMorphs anchorLocations imageMaps '
	classVariableNames: 'CSNonSeparators CSSeparators '
	poolDictionaries: ''
	category: 'Network-HTML Formatter'