RectangleMorph
	subclass: #PianoRollScoreMorph
	instanceVariableNames:
		'scorePlayer score colorForTrack lowestNote leftEdgeTime timeScale indexInTrack lastUpdateTick lastMutedState cursor selection timeSignature beatsPerMeasure notePerBeat showMeasureLines showBeatLines soundsPlaying soundsPlayingMorph movieClipPlayer'
	classVariableNames: 'NotePasteBuffer'
	poolDictionaries: ''
	category: 'Sound-Scores'