EToyCommunicatorMorph
	subclass: #AudioChatGUI
	instanceVariableNames:
		'mycodec myrecorder mytargetip myalert playOnArrival theConnectButton soundBlockNumber soundMessageID queueForMultipleSends transmitWhileRecording theTalkButton handsFreeTalking handsFreeTalkingFlashTime '
	classVariableNames: 'DebugLog LiveMessages NewAudioMessages PlayOnArrival '
	poolDictionaries: ''
	category: 'Morphic-Experimental'