takanawa

	self setPreferencesFrom: #(
		(alternativeScrollbarLook true)
		(alternativeWindowLook true)
		(canRecordWhilePlaying true)
		(classicNavigatorEnabled false)
		(eToyFriendly true)
		(haloTransitions true)
		(honorDesktopCmdKeys false)
		(includeSoundControlInNavigator true)
		(magicHalos true)
		(menuKeyboardControl false)
		(mouseOverHalos true)
		(preserveTrash true)
		(projectViewsInWindows true)
		(propertySheetFromHalo true)
		(showDirectionHandles true)
		(showProjectNavigator true)
		(soundQuickStart true)
		(soundStopWhenDone true)
		(uniTilesClassic false)
		(uniqueNamesInHalos true)
		(unlimitedPaintArea true)
)