standardSlotInfo
	"Answer a list of arrays which characterize etoy slots borne by this kind of morph -- in addition to those already defined by superclasses.  Implementors of this method are statically polled to contribute this information when the scripting system reinitializes its scripting info, which typically only happens after a structural change."

	^ #((borderWidth 	number		readWrite	getBorderWidth		setBorderWidth:)
		(borderColor		color		readWrite	getBorderColor		setBorderColor:)
		(bottom 			number		readWrite	getBottom			setBottom:)
		(color			color		readWrite	getColor				setColor:)
		(colorSees		boolean		readOnly	dummy				unused)
		(colorUnder		color		readOnly	getColorUnder		unused)
		(heading		number		readWrite	getHeading			setHeading:)
		(height 			number		readWrite	getHeight			setHeight:)
		(isOverColor		boolean		readOnly	dummy				unused)
		(isUnderMouse	boolean		readOnly	getIsUnderMouse		unused)
		(left 			number		readWrite	getLeft				setLeft:)
		(penDown		boolean		readWrite	getPenDown			setPenDown:)
		(penColor		color		readWrite	getPenColor			setPenColor:)
		(penSize 		number		readWrite	getPenSize			setPenSize:)
		(right 			number		readWrite	getRight			setRight:)
		(scaleFactor		number		readWrite	getScaleFactor		setScaleFactor:)
		(top 			number		readWrite	getTop				setTop:)
		(width 			number		readWrite	getWidth			setWidth:)
		(x 				number		readWrite	getX					setX:)
		(y				number		readWrite	getY				setY:))
