Object
	subclass: #EToyParameters
	instanceVariableNames: ''
	classVariableNames:
		'AlanDemoMode BadgePicPt CautionBeforeClosing CmdDotEnabled CoverSpiralPt FrozenPlayfieldBorderColor FrozenPlayfieldColor FullEToyGraphics GoButtonInScriptor ImagiPicPt KidsMode RunningPlayfieldBorderColor RunningPlayfieldColor StudioPicPt TransparentPlayfield WaltPicPoint '
	poolDictionaries: ''
	category: 'Experimental-EToy'