Object
	subclass: #ParseNode
	instanceVariableNames: 'comment '
	classVariableNames:
		'StdSelectors NodeThisContext Send NodeFalse LdInstLong LdLitIndType Jmp LdSuper LdThisContext SendType StdLiterals Store LdTrue Dup NodeSelf ShortStoP LdInstType NodeTrue LdSelf JmpLong CodeBases StdVariables LdFalse SendPlus JmpLimit CodeLimits SendLimit Bfp LdTempType LdNil BtpLong EndMethod StorePop LdMinus1 LdLitType SendLong NodeNil NodeSuper EndRemote Pop '
	poolDictionaries: ''
	category: 'System-Compiler'