readDataFrom: aDataStream size: varsOnDisk
	"Create an object based on the contents of aDataStream, which was
	   generated by the object¼s storeDataOn: method. Answer it.
	 This implementation reads back the instance-variables written by
	   Object>>storeDataOn:.
	 NOTE: This method must match its corresponding storeDataOn:
	   method. Also, it must send beginReference: after instantiating
	   the new object but before reading any objects from aDataStream
	   that might reference it.
	11/23/92 jhm: Changed to basicNew & basicNew: to match basicSize and because
		we then overwrite all instance & indexed vars.
	: allow fewer inst vars, and total remap for others.  Let object do it."
	| anObject cntInstVars cntIndexedVars |

	self halt.  "Use same method in the instance side"
	cntInstVars _ self instSize.
	anObject _ self isVariable
		ifTrue: [cntIndexedVars _ varsOnDisk - cntInstVars.
				cntIndexedVars < 0 ifTrue: [self error: 'Class needs to be reshaped'].
				self basicNew: cntIndexedVars]
		ifFalse: [self basicNew].

	^ anObject readDataFrom: aDataStream size: varsOnDisk