readDataFrom: aDataStream size: varsOnDisk
	"Make self be an object based on the contents of aDataStream, which was generated by the object's storeDataOn: method. Return self.  Must read both objects for the literals and bytes for the bytecodes."

	| lits |
	aDataStream beginReference: self.
	self objectAt: 1 put: aDataStream next.	"the header"
	lits _ self numLiterals + 1.	"counting header"
	2 to: lits do:
		[:ii | self objectAt: ii put: aDataStream next].
	lits*4+1 to: self basicSize do:
		[:ii | self basicAt: ii put: aDataStream byteStream next].
			"Get raw bytes directly from the file"
	^ self